### ISSUE TITLE
Feature Request: Front page blog icons should display with a fixed resolution so that the stack nicely

### ISSUE THREAD

**Issue by dnk8n** [themefisher/restaurant-hugo#10]
Currently it is possible for icons to look as follows:

![Screenshot from 2019-10-16 10-44-01](https://user-images.githubusercontent.com/3307753/66902988-efc7e800-f001-11e9-8758-a947355f9017.png)

It would also be desirable to only show multiples of 2, with the option to side-scroll or click a lick to expand to older blog posts. Please see https://github.com/themefisher/restaurant-hugo/issues/9 for more detail on this issue.

**Comment by Somrat37** [comment]
@dnk8n ,
i am sorry, i can't get you.

**Comment by dnk8n** [comment]
A blog image of any resolution or aspect ratio should be able to be
uploaded... And on the front page the blog text area should remain fixed.

**Comment by Somrat37** [comment]
@dnk8n ,
Blog item is now fixed-height
