### ISSUE TITLE
Feature Request: Ability to be able to make page content (as apposed to blog content)

### ISSUE THREAD

**Issue by dnk8n** [themefisher/restaurant-hugo#11]
Users might want the ability to create a detailed 'About us' page for example. It would look almost identical to a blog post, but with 2 important modifications.

1. Date is not important (Needs ability for date to not be displayed)
2. Should not be shown in blog section of Front page.

Currently I don't see a way to avoid either of these. Is there some other location to create a basic page.

I experimented and found that I could create a page like this:

```
---
title: about-us
image: /images/example.jpg
type: page
---
Some further detail about us...

```

Where else is `type` used? It could be useful in filtering out blog content from front page (e.g. only where `type: post` will it display on blog section of front page. This would solve `2.`

In the above `date` is not necessary but unfortunately it shows a confusing timestamp in the resulting page. It would be very useful to be able to hide the auto-generated timestamp when `type: page` for example.

**Comment by dnk8n** [comment]
An example of how the above page looks

![example](https://user-images.githubusercontent.com/3307753/66905143-96fa4e80-f005-11e9-8074-4abf0bc299e9.png)

**Comment by Somrat37** [comment]
@dnk8n ,
I am sorry about that, but this is an one page template, if you want to create another page then you need to create this page layout first. Or you can contact us at : themefisher@gmail.com
