### ISSUE TITLE
Documentation about params.preloader

### ISSUE THREAD

**Issue by dnk8n** [themefisher/restaurant-hugo#12]
I don't understand what this is doing? Where can I find information?

**Comment by Somrat37** [comment]
@dnk8n ,
if can enable or disable preloader by enable = true or false, then if you want any image, logo, or animation in preloader then give the location in `preloader = ` , like `preloader = images/preloader.gif` or if you don't want any logo or image then leave the preloader field empty, then it will show just a white screen when every component is loading. that's simple.
