### ISSUE TITLE
Refreshing multiple times -> White page

### ISSUE THREAD

**Issue by madsystem** [themefisher/restaurant-hugo#15]
If I hit refresh multiple times, the page will load (can see html source) but the browser only shows an white page.

**Comment by madsystem** [comment]
Seems to be realated with the preloader. If disabled the described problem does not occure.

**Comment by madsystem** [comment]
Moving `$(window).on('load', function () `  out e.g.:

`// Preloader js    
$(window).on('load', function () {
    $('.preloader').fadeOut(100);
})

$(document).ready(function () {`

seems to fix it. Thanks for the nice template!

**Comment by Somrat37** [comment]
@madsystem 

thanks for your concern, i'll fix it in the next update.
