### ISSUE TITLE
feature request: multilanguage support

### ISSUE THREAD

**Issue by mbasnak** [themefisher/restaurant-hugo#19]
Is it possible to add multilanguage support?

**Comment by Somrat37** [comment]
Yes, it is possible. If you have knowledge about hugo, you can do it. Or you can contact us for our paid support at : themefisher@gmail.com

**Comment by mbasnak** [comment]
I have knowledge about Hugo, and managed to get the blog posts and menu bar to display correctly in both languages. However, the way you structured your website using homepage.yml is not mainstream. For example, the section 'about' of the sebsite is there instead of belonging to a different content folder. We then have:

```
about:
    enable : true
    image : "images/cooker-img.png"
    title : "About  <span> this blog </span>"
```

I would like to add a language option like we can do in the config.toml with [[language.es.menu.main]] for example, but applied to that 'about' or other sections from the homepage.
I tried adding something like
```
{{ if eq $.Site.Language.LanguageName "es" }}
```
to the 'about.html' file but that doesn't work.
Could you please provide me some minimal guidance?
Thanks
