### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by drfurtado** [themefisher/restaurant-hugo#20]
I have two questions.
Question 1: How to delete the date for blog posts? I am using "posts" for another purpose and do not really need the data on "posts". https://skinica.netlify.com/acne-treatment/

Question 2: How to replate the middle widget in the footer (blog posts) and replace it with another set of photo stream? https://skinica.netlify.com/#contact-us

Screenshots
https://www.screencast.com/t/y6oOYnbsnLB5
https://www.screencast.com/t/KSVaj4UHp

Thanks a lot

**Comment by Somrat37** [comment]
For this, you need to know some basic html. and do some modification on index.html file. Or you can contact us for our paid support at : themefisher@gmail.com
