### ISSUE TITLE
Featured Works Slider Question

### ISSUE THREAD

**Issue by mkz71** [themefisher/restaurant-hugo#21]
Where is exactly this part in red circle in the code?
I can't find it.

<img width="551" alt="Screenshot 2020-09-06 134550" src="https://user-images.githubusercontent.com/6776374/92331867-99173280-f047-11ea-865e-26ca8eb7b0f5.png">

**Comment by developer-evan** [comment]
here is the line https://github.com/themefisher/restaurant-hugo/blob/ec1455128dc769a098f942e979922f5154a04324/static/js/main.js#L25
