### ISSUE TITLE
Cannot use categories and tags on blog posts

### ISSUE THREAD

**Issue by romain-nio** [themefisher/restaurant-hugo#22]
Hello,

I recently downloaded your template "restaurant-hugo". Many thanks for it, it's really great.

I want to use the template for a small personal blog to host cooking recipes.

I'd like to create several blog posts with tags and/or categories and after use the hugo native feature to generate dynamic pages like : 
**/tags/chocolate** or **/categories/salty**

I created some fake posts with tags and categories params and tried to access **/categories/salty** but it's seems that the template is not working as I was expecting : the "latest blog" component is displayed with ALL articles instead of only the ones with the specific categorie.

I tested with the native ananke template and the tags/categories are working well with my article.

Is-it something normal ? 

Many thanks,
Romain.

**Comment by somratpro** [comment]
Hello @romain-nio 

I understand that you need a taxonomy filter for this template, but we don't have it right now in this template. I am happy to say that we are now available for hiring. you can hire us for any kind of Hugo customization. contact us at mehedi@themefisher.com for theme customization. thank you.
