### ISSUE TITLE
How can I change the image size in the slide gallery and height of the menu bar?

### ISSUE THREAD

**Issue by ll3N1GmAll** [themefisher/restaurant-hugo#3]
How can I change the image size in the slide gallery? 

Also, the menu bar is partially obscuring too much of the header.png image for my site when viewed on mobile screens (even when horizontal). How can I change the dimensions of the floating menu bar? Thanks to all who reply!

**Comment by ll3N1GmAll** [comment]
For the floating menu.nav bar, is there a transparency setting I could change? That would resolve one of my issues.

**Comment by Somrat37** [comment]
@ll3N1GmAll 
sorry for late reply.
If you want to change the navigation height or transparency, and change the image size, you have to knowledge about css, you need to write some custom css for make it happen. Or you can contact us at themefisher@gmail.com for our support, thanks.
