### ISSUE TITLE
Feature proposal/request - clickable images in Featured Menu / Photostream sections

### ISSUE THREAD

**Issue by tukak** [themefisher/restaurant-hugo#5]
It would be great if images in Featured Menu / Photostream sections could be clicked and bigger image then appears on screen

**Comment by dnk8n** [comment]
This would be great. Also allow captions which are preferably markdown (and/or html) and can therefore be hyperlinked.

**Comment by Somrat37** [comment]
@tukak @dnk8n ,
this functionality is now available, please pull the latest code
