### ISSUE TITLE
Feature Request: Ability to switch off image tint currently present in front of images.

### ISSUE THREAD

**Issue by dnk8n** [themefisher/restaurant-hugo#6]
This default could be useful to people but should not be a default because it might not be applicable to most websites.

**Comment by dnk8n** [comment]
I just realized that there is a way to achieve the outcome desired. Download image below and save it over `.../static/images/overlay-pattern.png` (and possible `.../static/images/overlay-pattern2.png`)

![overlay-pattern](https://user-images.githubusercontent.com/3307753/66907575-d75bcb80-f009-11e9-937e-0f09edfb8d18.png)

**Comment by Somrat37** [comment]
@dnk8n , 
thanks for your concern, this functionality is now available
