### ISSUE TITLE
Feature Request: Allow hyperlinks in the footer 'contact info' section

### ISSUE THREAD

**Issue by dnk8n** [themefisher/restaurant-hugo#7]
Similar to the social icon hyperlinks, except the ability for an address text to link to Google Maps for example

**Comment by Somrat37** [comment]
@dnk8n ,
you can do it now

**Comment by dnk8n** [comment]
How is a link added? Is there documentation about the latest changes?

HTML does not work.

e.g.

This does not work in toml:

```
[[params.footer.contactItem]]
content = "Adjacent to Mvubu Falls Lodge,\nMnyamatsini,\nMbabane,\neSwatini\n\n<a href=\"https://goo.gl/maps/2SpiERmytpCaGDoE6\">Click for map</a>"
icon = "fa fa-map-marker"
title = "Address"
```

**Comment by Somrat37** [comment]
@dnk8n ,
I am sorry about that, it was an mistake, can you please pull the code again now? and don't use html in content, use markdown. 
content = "Adjacent to Mvubu Falls Lodge,<br>Mnyamatsini,<br>Mbabane,<br>eSwatini<br><br>[Click for map](https://goo.gl/maps/2SpiERmytpCaGDoE6\)"

**Comment by dnk8n** [comment]
Great. Thanks very much.

On that note, it would be very useful for many of the description fields to
also support markdown.

Appreciate your maintenance of this awesome theme!
