### ISSUE TITLE
Feature Request: A limit to how many blog posts exist on the front page

### ISSUE THREAD

**Issue by dnk8n** [themefisher/restaurant-hugo#9]
From what I can see, as blog content is added, so does the list on the front page.

It would be desirable to show 4-6 of the latest blogs and then a hyperlink to view older content.

Alternatively a side-scroller could enable the user to click through all blog content on the homepage without taking up space on the front page.

**Comment by Somrat37** [comment]
@dnk8n ,
this feature is now available, please pull the latest code. thanks
